import {it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {cloneProject,parseProject,type Model} from '../packages/domain/src/index';
import {prepareSolver,emptyLoad} from '../packages/frame2d-solver/src/index';
import {elasticCurve,engineeringDebug} from '../packages/frame2d-solver/src/recovery';
import {generateModel} from '../packages/model-generator/src/index';
import {waterLoads,resultant,combine} from '../packages/load-engine/src/index';
import {analyze} from '../packages/result-engine/src/index';
function beam():Model{return {nodes:[{id:0,x:0,y:0},{id:1,x:6,y:0}],elements:[{id:0,i:0,j:1,E:25e6,A:.4,I:.4**3/12,member:'T1',kind:'top',thickness:.4,rigid:false}],members:[{id:'T1',kind:'top',thickness:.4,elements:[0]}],bottomNodes:[],width:6,height:0,wallX:[]};}
it('V3 exact UDL deflection: simple and fixed ends, even with all zero nodal DOFs',()=>{for(const fixed of [false,true]){const m=beam(),load=emptyLoad(m);load.element[0].qy=-12;const sol=prepareSolver(m).factor(fixed?[0,1,2,3,4,5]:[0,1,4])(load),EI=m.elements[0].E*m.elements[0].I,c=elasticCurve(6,EI,sol.endForces[0],load.element[0],sol.u[1],sol.u[2]);expect(c.value(3)).toBeCloseTo(-(fixed?1:5)*12*6**4/(384*EI),11);expect(c.extrema().some(x=>Math.abs(x-3)<1e-8)).toBe(true);expect(c.value(6)).toBeCloseTo(0,11);}});
it('V3 cantilever point particular solution and arbitrary patch/triangle end compatibility',()=>{const m=beam(),EI=m.elements[0].E*m.elements[0].I;for(const q of [{qx:0,qy:0,points:[{x:6,px:0,py:-10}]},{qx:0,qy:0,patches:[{a:1,b:4,qx:0,qy:-3,qyEnd:-17}]},{qx:0,qy:0,qyEnd:-20}]){const load=emptyLoad(m);load.element[0]=q;const s=prepareSolver(m).factor([0,1,2])(load),c=elasticCurve(6,EI,s.endForces[0],q,0,0);expect(c.value(6)).toBeCloseTo(s.u[4],10);expect(c.slope(6)).toBeCloseTo(s.u[5],10);if('points' in q)expect(c.value(6)).toBeCloseTo(-10*6**3/(3*EI),10);}});
it('IW dry zero, full rectangular water weight, and natural partition cancellation',()=>{for(const cells of [1,3])for(const depth of [0,.13,2.5]){const p=cloneProject();p.geometry.cells=cells;p.water.depth=depth;const m=generateModel(p),w=waterLoads(p,m);expect(w.resultant.fx).toBeCloseTo(0,10);expect(w.resultant.fy).toBeCloseTo(-9.80665*cells*3*depth,9);if(!depth){expect(w.sides).toHaveLength(0);expect(w.bottoms).toHaveLength(0);expect(w.net.element.every(q=>q.qx===0&&q.qy===0&&!q.patches?.length)).toBe(true);}if(cells===3){const pair=w.sides.filter(s=>s.member==='P1');const net=combine(m,pair.map(s=>[s.load,1]),'partition');expect(resultant(m,net).fx).toBeCloseTo(0,12);for(const e of m.elements.filter(e=>e.member==='P1')){const q=net.element[e.id];expect((q.patches??[]).reduce((s,v)=>s+v.qy,0)).toBeCloseTo(0,12);}}}});
it('V2 baseline M/V/N and displacements unchanged when dry',()=>{const base=JSON.parse(readFileSync('tests/v2-baseline.json','utf8'));for(const b of base){const p=cloneProject();p.soil.support=b.support;const r=analyze(p);r.manual.u.forEach((v,i)=>expect(v).toBeCloseTo(b.u[i],10));r.manual.endForces.forEach((f,i)=>f.forEach((v,j)=>expect(v).toBeCloseTo(b.forces[i][j],7)));r.envelope.forEach((e,i)=>{for(const k of ['Mmin','Mmax','Vmin','Vmax','Nmin','Nmax'] as const)expect(e[k].value).toBeCloseTo(b.envelope[i][k].value,7);});}});
it('Joint equilibrium includes loads and reactions; rigid Joint and Face moments differ',()=>{const p=cloneProject();p.water.depth=1.8;const r=analyze(p);expect(Math.max(...r.debug.joints.flatMap(j=>j.residual.map(Math.abs)))).toBeLessThan(1e-7);expect(r.debug.members.some(m=>m.ends.some(e=>Math.abs(e.faceForce[2]-e.jointForce[2])>1))).toBe(true);expect(r.deflections.every(d=>d.down.mm>=0&&d.down.xL>=0&&d.down.xL<=1)).toBe(true);expect(r.trace.every(t=>t.formula&&t.substitution&&t.unit&&t.source)).toBe(true);});
it('V2 JSON explicitly migrates dry with IW factor 1',()=>{const p:any=cloneProject();p.schemaVersion=2;delete p.water;delete p.combination.water;const migrated=parseProject(JSON.stringify(p));expect(migrated.schemaVersion).toBe(3);expect(migrated.water.depth).toBe(0);expect(migrated.combination.water).toBe(1);});
it('rigid-end joint moment includes the exact shear lever arm',()=>{const m=beam();m.nodes=[{id:0,x:0,y:0},{id:1,x:2,y:0,master:0},{id:2,x:6,y:0}];m.elements=[{...m.elements[0],i:0,j:1,rigid:true},{...m.elements[0],id:1,i:1,j:2}];m.members[0].elements=[0,1];const load=emptyLoad(m);load.nodal[7]=-10;const sol=prepareSolver(m).factor([0,1,2])(load),d=engineeringDebug(m,sol,load),i=d.members[0].ends[0];expect(i.faceForce[1]).toBeCloseTo(10,8);expect(i.faceForce[2]).toBeCloseTo(40,8);expect(i.jointForce[2]).toBeCloseTo(60,8);expect(Math.max(...d.joints.flatMap(j=>j.residual.map(Math.abs)))).toBeLessThan(1e-8);});
it('relative deflection removes common settlement and rigid rotation',async()=>{const {topDeflections}=await import('../packages/frame2d-solver/src/recovery');const m=beam(),load=emptyLoad(m);load.element[0].qy=-12;const sol=prepareSolver(m).factor([0,1,4])(load),base=topDeflections(m,sol,load,'base')[0];const moved=structuredClone(sol);m.nodes.forEach(n=>{moved.u[n.id*3+1]+=.12+.002*n.x;moved.u[n.id*3+2]+=.002;});const shifted=topDeflections(m,moved,load,'shifted')[0];expect(shifted.down.mm).toBeCloseTo(base.down.mm,10);expect(shifted.down.xL).toBeCloseTo(.5,10);});
it('one flexible element per member is supported without requiring deflection mesh refinement',()=>{const p=cloneProject();p.geometry.divisions=1;p.water.depth=2.5;const r=analyze(p);expect(r.model.members.every(m=>m.elements.filter(i=>!r.model.elements[i].rigid).length===1)).toBe(true);expect(r.deflections.every(d=>Number.isFinite(d.down.mm))).toBe(true);expect(Math.max(...r.debug.joints.flatMap(j=>j.residual.map(Math.abs)))).toBeLessThan(1e-7);});
