import {useEffect,useRef,useState} from 'react';
import {cloneProject,parseProject,validateProject,type Project} from '../../../packages/domain/src/index';
import type {Analysis} from '../../../packages/result-engine/src/index';
import {ruleStatus,codeRegister} from '../../../packages/codes-tw/src/index';
import {cadData} from '../../../packages/export-cad/src/index';
import {generateModel} from '../../../packages/model-generator/src/index';
import {loadAudit} from '../../../packages/load-engine/src/index';
import Viewer,{type ViewMode} from './Viewer';
const STORAGE='box-culvert-project-v2';
const n=(v:number)=>Number.isFinite(v)?v.toLocaleString('en-US',{maximumFractionDigits:2,minimumFractionDigits:2}):'—';
function initial(){try{const saved=localStorage.getItem(STORAGE);if(saved)return parseProject(saved);}catch{/* An incompatible autosave cannot replace a valid default. */}return cloneProject();}
function download(data:BlobPart,name:string,type:string){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function Field({label,value,unit,onChange,step=0.05,min,max}:{label:string;value:number;unit?:string;onChange:(v:number)=>void;step?:number;min?:number;max?:number}){return <label className="field"><span>{label}</span><div><input type="number" value={Number.isFinite(value)?value:''} step={step} min={min} max={max} onChange={e=>onChange(e.target.value===''?NaN:Number(e.target.value))}/>{unit&&<small>{unit}</small>}</div></label>;}
export default function App(){
 const [project,setProject]=useState<Project>(initial),[result,setResult]=useState<Analysis|null>(null),[panel,setPanel]=useState('geometry'),[tab,setTab]=useState('forces'),[view,setView]=useState<ViewMode>('geometry'),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[error,setError]=useState(''),[notice,setNotice]=useState(()=>localStorage.getItem('box-culvert-project-v1')&&!localStorage.getItem(STORAGE)?'偵測到 V1 暫存，原資料已保留。本版載重定義變更，請重新確認 DL、土壓與車载設定，未自動套用舊值。':''),[exporting,setExporting]=useState(false);
 const worker=useRef<Worker|null>(null),file=useRef<HTMLInputElement>(null);
 let validation='';try{validateProject(project);}catch(e){validation=(e as Error).message;}
 useEffect(()=>{if(!validation){try{localStorage.setItem(STORAGE,JSON.stringify(project));}catch{setNotice('瀏覽器暫存不可用，請下載 Project JSON 保存。');}}},[project,validation]);
 useEffect(()=>()=>worker.current?.terminate(),[]);
 const edit=(group:'geometry'|'material'|'soil'|'vehicle'|'combination',key:string,value:unknown)=>{setProject(p=>({...p,[group]:{...p[group],[key]:value}}));setResult(null);setError('');setView('geometry');};
 const field=(group:'geometry'|'material'|'soil'|'vehicle'|'combination',key:string,label:string,unit:string,step=0.05,min?:number,max?:number)=><Field key={group+key} label={label} value={(project[group] as unknown as Record<string,number>)[key]} unit={unit} step={step} min={min} max={max} onChange={v=>edit(group,key,v)}/>;
 function run(mode:'manual'|'envelope'){
  if(validation)return;worker.current?.terminate();setBusy(true);setError('');setProgress(0);const w=new Worker(new URL('./analysis.worker.ts',import.meta.url),{type:'module'});worker.current=w;
  w.onmessage=e=>{if(e.data.type==='progress')setProgress(e.data.done/e.data.total);if(e.data.type==='result'){setResult(e.data.result);setBusy(false);setProgress(1);w.terminate();}if(e.data.type==='error'){setError(e.data.error);setBusy(false);w.terminate();}};
  w.onerror=e=>{setError(e.message||'分析執行失敗');setBusy(false);w.terminate();};w.postMessage({project,mode});
 }
 async function exportXlsx(){if(!result)return;setExporting(true);try{const {workbookBytes}=await import('../../../packages/export-xlsx/src/index');const bytes=await workbookBytes(result);download(bytes as ArrayBuffer,'箱涵計算.xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');setNotice('已下載 Excel：包含輸入、包絡、控制工況、配筋試算與計算追溯。');}catch(e){setError((e as Error).message);}finally{setExporting(false);}}
 let audit:ReturnType<typeof loadAudit>|null=null;try{if(!validation)audit=loadAudit(project,generateModel(project));}catch{/* Validation owns feedback. */}
 const maxM=result?Math.max(...result.envelope.flatMap(e=>[Math.abs(e.Mmin.value),Math.abs(e.Mmax.value)])):0;
 const maxV=result?Math.max(...result.envelope.flatMap(e=>[Math.abs(e.Vmin.value),Math.abs(e.Vmax.value)])):0;
 const maxDisp=result?Math.max(...result.manual.u.filter((_,i)=>i%3===1).map(v=>Math.abs(v)*1000)):0;
 return <div className="app">
  <aside className="rail"><div className="brand-mark">▥</div><span>BC</span><div className="rail-line"/><span className="rail-current">01</span><div className="rail-bottom">V2</div></aside>
  <div className="workspace"><header><div><div className="eyebrow">CIVIL ENGINEERING / STRUCTURAL TOOLS</div><h1>箱涵計算工作室 <span>Box Culvert</span></h1></div><div className="header-right"><span className="version">V2 · ALPHA 1</span><a href="https://github.com/ChengKaiShih/Box-Culvert-Caculate" target="_blank" rel="noreferrer">GitHub ↗</a></div></header>
  <div className="projectbar"><div className="projectname"><span className="dot"/><input aria-label="專案名稱" value={project.name} maxLength={200} disabled={busy} onChange={e=>{setProject({...project,name:e.target.value});setResult(null);}}/><span className="muted">Project / 001</span></div><div className="actions"><button disabled={busy} onClick={()=>file.current?.click()}>匯入專案</button><button disabled={!!validation} onClick={()=>download(JSON.stringify(project,null,2),'箱涵專案.json','application/json')}>儲存 JSON ↓</button><input ref={file} hidden type="file" accept=".json,application/json" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{const p=parseProject(await f.text());setProject(p);setResult(null);setView('geometry');setError('');setNotice('專案已匯入。請重新執行分析。');}catch(e){setError(`匯入失敗：${(e as Error).message}`);}finally{e.target.value='';}}}/></div></div>
  <div className="statusline"><span className="statusdot"/>{ruleStatus}<span className="statusdetail">規範係數及設計細部待覆核；本版提供模型分析與斷面試算。</span></div>
  {notice&&<div className="notice" role="status">{notice}<button aria-label="關閉提示" onClick={()=>setNotice('')}>×</button></div>}
  {(error||validation)&&<div className="error" role="alert">{error||validation}</div>}
  <main><section className="input-panel"><div className="panel-title"><h2>模型設定</h2><span>INPUT</span></div><div className="input-tabs">{[['geometry','幾何'],['material','材料'],['soil','地盤／支承'],['vehicle','載重'],['combination','組合']].map(([id,label])=><button key={id} className={panel===id?'active':''} onClick={()=>setPanel(id)}>{label}</button>)}</div>
  <fieldset disabled={busy} className="fields">
  {panel==='geometry'&&<><div className="section-label">01 / 斷面配置</div>{field('geometry','cells','箱涵孔數','孔',1,1,6)}<div className="field-row">{field('geometry','clearWidth','各孔淨寬','m',0.1)}{field('geometry','clearHeight','淨高','m',0.1)}</div><div className="section-label">02 / 構件厚度</div><div className="field-row">{field('geometry','top','頂板','m')}{field('geometry','bottom','底板','m')}</div><div className="field-row">{field('geometry','wall','側牆 A1 / A2','m')}{field('geometry','partition','中隔板 Pn','m')}</div><div className="section-label">03 / 分析細部</div>{field('geometry','haunch','倒角尺寸（1:1）','m')}<details><summary>進階分析設定</summary>{field('geometry','divisions','每構件柔性段分割','段',1,2,12)}<p className="help">2～12 整數；0 無效。分割為連續分析元素，不增加鉸接或施工縫。</p></details><p className="help">倒角自動配置於各孔四角，以完全剛性連結納入分析。所有孔採等淨寬配置。</p></>}
  {panel==='material'&&<><div className="section-label">01 / 材料強度</div>{field('material','fcKgfCm2',"混凝土 f′c",'kgf/cm²',10)}{field('material','fyKgfCm2','鋼筋 fy','kgf/cm²',100)}{field('material','elasticModulusMPa','混凝土彈性模數 E','MPa',1000)}{field('material','concreteWeight','混凝土單位重','kN/m³',0.1)}<div className="section-label">02 / 配筋試算</div>{field('material','coverMm','最外層主筋保護層','mm',5)}{field('material','barDiameterMm','試配鋼筋直徑','mm',1)}<p className="help">各構件採雙面等量鋼筋。直徑按輸入之圓形面積計算；保護層、間距、錨定與彎折仍須依施工條件核對。</p></>}
  {panel==='soil'&&<><div className="section-label">地盤／支承</div><label className="field"><span>基底模式</span><select value={project.soil.support} onChange={e=>edit('soil','support',e.target.value)}><option value="winkler">Winkler・線性地盤彈簧</option><option value="rigid">Rigid Base・剛性基底</option></select></label>{project.soil.support==='winkler'&&field('soil','ks','地盤反力係數 ks','kN/m³',1000)}<p className="help">此支承選項是數值邊界條件，不自動判定是否符合規範等值土壓法的基礎適用條件。地下水、浮力未計。</p></>}
  {panel==='vehicle'&&<><div className="section-label">01 / DC 自重・自動計算</div><p className="help">每 1m 分析帶，未乘組合係數</p>{audit&&<><table className="audit-table"><tbody>{audit.parts.map(v=><tr key={v.name}><td>{v.name}</td><td>{n(v.weight)} kN</td></tr>)}<tr><th>幾何總重</th><td>{n(audit.geometric)} kN</td></tr><tr><th>模型施加</th><td>{n(audit.applied)} kN</td></tr><tr><th>差值</th><td>{audit.difference.toExponential(2)} kN</td></tr></tbody></table></>}
<div className="section-label">02 / DL 附加靜載重</div>{field('soil','additionalDead','頂板等值均佈永久載重','kPa',1)}<p className="help">不含箱涵自重與覆土重；護欄等局部效應未模擬。背填土地表超載本版不計入。</p>
<div className="section-label">03 / EV・EH 土壓</div>{field('soil','cover','頂板上覆土厚度 h','m',0.1)}<label className="field"><span>土壓計算方式</span><select value={project.soil.mode} onChange={e=>edit('soil','mode',e.target.value)}><option value="code">規範等值流體法</option><option value="active">自訂 γ + Ka 主動土壓</option></select></label>
{project.soil.mode==='active'?<>{field('soil','unitWeight','土壤單位重 γ','kN/m³',0.1)}{field('soil','ka','主動土壓係數 Ka','',0.05)}<p className="help">採主動土壓假設；設計者須確認拘束及位移条件，不自動加上規範兩組 EH。</p></>:<p className="help">§3.3：EV 單位重 18.85；EH 4.71／9.42 kN/m³ 分別分析，不再乘 Ka。須符合條文埋設與基礎條件。</p>}
<label className="field"><span>土壓採用依據／條件確認</span><textarea value={project.soil.source} onChange={e=>edit('soil','source',e.target.value)}/></label>
{audit&&<div className="help">{audit.rows.slice(1).map(v=><p key={v.name}>{v.name}：{v.formula} = {n(v.value)} {v.unit}；合力 {n(v.force)} kN</p>)}{audit.earth.filter((_,i)=>project.soil.mode==='code'||i===1).map(v=><p key={v.variant}>EH {v.variant}：頂 {n(v.top)}／底 {n(v.bottom)} kPa；每側合力 {n(v.force)} kN（牆中心線模型）</p>)}</div>}
<div className="section-label">04 / LL 設計車輛 →</div><label className="field"><span>車載型式</span><select value={project.vehicle.type} onChange={e=>edit('vehicle','type',e.target.value)}><option value="HS20x1.25">HS20-44 × 1.25</option><option value="HS20">HS20-44</option><option value="HS15">HS15-44</option><option value="H20">H20-44</option><option value="H15">H15-44</option><option value="none">無車載</option></select></label>{field('vehicle','position','前軸位置（由 A1 起）','m',0.25)}{field('vehicle','rearSpacing','HS 後軸距','m',0.25,4.25,9.15)}{field('vehicle','barrelWidth','支承板橫向寬度（沿水流）','m',0.5)}{field('vehicle','wheelSpacing','左右輪線間距','m',0.1)}{audit&&<p className="help">{audit.rules.reason}<br/>S = {n(audit.rules.S)} m；L = {n(audit.rules.L)} m<br/>{audit.rules.deep?`擴散邊長 ${n(audit.rules.length)} m；分布寬 ${n(audit.rules.width)} m；${audit.rules.joined?'左右輪線合併':'輪線未重疊'}`:`集中輪重；E = ${n(audit.rules.E)} m（§4.3.3(2)）`}<br/>衝擊 I = {n(audit.rules.impact*100)}%。h≤0.6m 歸入淺覆土。單一車輛，尚未含多車道。</p>}<div className="section-label">03 / Auto Envelope</div>{field('vehicle','step','移動掃描步距','m',0.1,0.1,2)}<label className="check"><input type="checkbox" checked={project.vehicle.scanRearSpacing} onChange={e=>edit('vehicle','scanRearSpacing',e.target.checked)}/>掃描 HS 後軸距（4.25～9.15 m）</label><p className="help">掃描正、反行車方向；規範模式兩組側土壓，自訂模式一組；建議以步距減半再比對控制值。</p></>}
  {panel==='combination'&&<><div className="section-label">01 / 使用者載重組合</div><p className="help">初始係數皆為 1.0，供模型驗證。正式強度設計應輸入適用規範之組合；本版不自動宣告規範合格。</p>{field('combination','dead','DC・自重','',0.05)}{field('combination','earthVertical','EV・垂直土壓','',0.05)}{field('combination','earthHorizontal','EH・側向土壓','',0.05)}{field('combination','additionalDead','DL・附加靜載重','',0.05)}{field('combination','live','LL・車載含衝擊','',0.05)}<label className="field"><span>組合名稱</span><input value={project.combination.name} onChange={e=>edit('combination','name',e.target.value)}/></label><label className="field"><span>規範／設計依據</span><textarea value={project.combination.source} onChange={e=>edit('combination','source',e.target.value)}/></label></>}
  </fieldset><div className="run-panel"><button className="primary" disabled={busy||!!validation} onClick={()=>run('envelope')}>▶ 執行車載包絡 <span>Auto Envelope</span></button><button className="secondary" disabled={busy||!!validation} onClick={()=>run('manual')}>計算目前車位</button>{busy&&<><progress value={progress} max="1"/><div className="progress-text">分析中 {Math.round(progress*100)}%<button onClick={()=>{worker.current?.terminate();setBusy(false);setNotice('分析已取消。');}}>取消</button></div></>}<p>輸入自動暫存於此瀏覽器</p></div></section>
  <section className="output-panel"><div className="section-heading"><div><div className="eyebrow">MODEL OVERVIEW</div><h2>參數化箱涵模型</h2></div><div className="model-tag">{project.geometry.cells} 孔 <span>／</span> 2D FRAME</div></div>
  <div className="viewer-card"><div className="viewer-tools">{([['geometry','幾何 / 載重'],['M','彎矩 M'],['V','剪力 V'],['N','軸力 N'],['deformation','變形']] as const).map(([id,label])=><button key={id} className={view===id?'active':''} disabled={id!=='geometry'&&!result} onClick={()=>setView(id)}>{label}</button>)}<span>{view==='geometry'?'即時預覽':'手動車位・EH_max 單一工況'}</span></div><Viewer project={project} result={result} mode={view}/><div className="viewer-footer"><span><i className="legend concrete"/>RC 斷面</span><span><i className="legend load"/>垂直載重</span><span>縱向＝行車方向・橫向＝水流方向</span><span className="last">{result?`${result.model.nodes.length} 節點 · ${result.model.elements.length} 元素`:'建立模型後可分析'}</span></div></div>
  <div className="metrics"><div><span>最大絕對彎矩</span><strong>{result?n(maxM):'—'}<small>kN·m/m</small></strong><em>{project.soil.mode==='code'?'兩組土壓 + 車載工況':'自訂主動土壓 + 車載工況'}</em></div><div><span>最大絕對剪力</span><strong>{result?n(maxV):'—'}<small>kN/m</small></strong><em>各構件包絡</em></div><div><span>目前車位垂直位移</span><strong>{result?n(maxDisp):'—'}<small>mm</small></strong><em>EH_max · 服務性需另核</em></div><div><span>分析工況</span><strong>{result?result.cases.toLocaleString():'—'}<small>cases</small></strong><em>{result?`${(result.durationMs/1000).toFixed(2)} 秒 · ${result.mode==='envelope'?'離散包絡':'手動位置'}`:'尚未執行'}</em></div></div>
  <div className="results-card"><div className="results-header"><div className="result-tabs">{[['audit','載重核對'],['forces','內力包絡'],['rc','配筋試算'],['trace','計算追溯'],['notes','適用範圍']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div><div className="export-actions"><button disabled={!result||exporting||busy} onClick={exportXlsx}>{exporting?'匯出中…':'Excel ↓'}</button><button disabled={!result||busy} onClick={async()=>{if(result){const {printReport}=await import('../../../packages/export-pdf/src/index');printReport(result);setNotice('請在列印視窗選擇「另存為 PDF」。');}}}>PDF / 列印</button><button disabled={!result||busy} onClick={()=>result&&download(JSON.stringify(cadData(result),null,2),'箱涵CAD.json','application/json')}>CAD JSON ↓</button></div></div>
  {!result&&tab!=='notes'?<div className="empty"><div className="empty-icon">▤</div><h3>模型就緒，開始第一筆分析</h3><p>設定斷面與載重後，執行目前車位或車載包絡。<br/>修改輸入後，結果會清除並等待重新分析。</p></div>:<>
  {tab==='audit'&&result&&<div className="notes"><h3>手動組合整體平衡（外力＋反力）</h3><p>ΣFx = {result.balance.fx.toExponential(3)} kN；ΣFy = {result.balance.fy.toExponential(3)} kN；ΣMz = {result.balance.mz.toExponential(3)} kN·m</p><p>自重幾何／模型差值：{result.audit.difference.toExponential(3)} kN</p><h3>頂板活載彎矩比較・kN·m/m</h3><p>列出各構件活載最大絕對值；候選較小值僅供人工核對，尚未按逐截面正負彎矩折減 RC 需求。</p><table><thead><tr><th>構件</th><th>§4.4 擴散</th><th>§4.3 集中輪重</th><th>候選較小值</th></tr></thead><tbody>{result.liveComparison.map(v=><tr key={v.member}><td>{v.member}</td><td>{n(v.fill)}</td><td>{n(v.plate)}</td><td>{n(v.adopted)}</td></tr>)}</tbody></table></div>}
  {tab==='forces' &&result&&<><div className="table-scroll"><table><thead><tr><th>構件</th><th>M min</th><th>M max</th><th>V min</th><th>V max</th><th>N min</th><th>N max</th></tr></thead><tbody>{result.envelope.map(e=><tr key={e.member}><td><b>{e.member}</b><small>{e.member.startsWith('T')?'頂板':e.member.startsWith('B')?'底板':'牆'}</small></td>{(['Mmin','Mmax','Vmin','Vmax','Nmin','Nmax'] as const).map(k=><td key={k} title={`${e[k].caseId}｜車位 ${e[k].position.toFixed(2)} m｜軸距 ${e[k].spacing} m`}>{n(e[k].value)}</td>)}</tr>)}</tbody></table></div><p className="table-note">M：kN·m/m；V、N：kN/m（拉力為正）。懸停數值可查看控制車位，完整工況見 Excel。剛域內不作柔性截面配筋判定。</p></>}
  {tab==='rc'&&result&&<>{result.minVerticalReaction < -1e-6&&<p className="error">地盤出現拉力反力，須另作接觸分析；以下配筋不可作為設計結果。</p>}<p className="inline-warning">N–M 強度為雙面等量配筋試算。剪力、裂縫與細部尚未完整檢核，不能作為施工配筋圖。</p><div className="table-scroll"><table><thead><tr><th>構件</th><th>雙面各配置</th><th>As / 每面</th><th>需求比</th><th>判讀</th></tr></thead><tbody>{result.rc.map(r=><tr key={r.member}><td><b>{r.member}</b></td><td>Ø{r.diameter} @ {r.spacing??'—'} mm</td><td>{n(r.asPerFace)} <small>mm²/m</small></td><td>{r.ratio>999?'超出範圍':n(r.ratio)}</td><td><span className={r.ratio<=1?'tag':'tag warn'}>{r.status}</span></td></tr>)}</tbody></table></div></>}
  {tab==='trace'&&result&&<div className="trace-list">{result.trace.map((t,i)=><details key={i} open={i<3}><summary><span>{String(i+1).padStart(2,'0')}</span>{t.stage}</summary><code>{t.expression}</code><p>{t.detail}</p><small>依據：{t.source}</small></details>)}</div>}
  {tab==='notes'&&<div className="notes"><h3>分析範圍與規範版本</h3><p>本次交付為 V2 開發試算版。已完成的分析與輸出可操作；尚未完成的規範檢核不顯示為合格。</p><ul>{(result?.warnings??['1～6 孔等淨寬 RC 箱涵；1 m 帶寬、線彈性剛架、完全剛性倒角。','Winkler 為雙向線性彈簧，出現拉力需另作離地接觸分析。','車載採單一設計車輛；多車道與車道載重尚未完成，§4.3／4.4 比較未折減 RC 需求。','配筋僅作 N–M 斷面試算；剪力、裂縫、溫縮、錨定、搭接及倒角鋼筋細部待完成。','尚未分析地下水、浮力、地震、施工階段、差異沉陷與新舊箱涵植筋。']).map((s,i)=><li key={i}>{s}</li>)}</ul>{codeRegister.map(c=><div className="source" key={c.id}><a href={c.url} target="_blank" rel="noreferrer">{c.title} ↗</a><span>{c.version}</span><small>{c.status}</small></div>)}</div>}
  </>}</div>
  <footer><span>BOX CULVERT / 工程計算・清楚可追溯</span><span>{result?`求解殘差 ${result.maxResidual.toExponential(2)}`:'前端本機計算・資料不傳送伺服器'}</span></footer>
  </section></main></div></div>;
}
