import type {Analysis} from '../../result-engine/src/index';
const escape=(s:unknown)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const num=(n:number)=>Number.isFinite(n)?n.toFixed(3):'—';
export function reportHtml(r:Analysis){
 const table=(headers:string[],rows:unknown[][])=>`<table><thead><tr>${headers.map(h=>`<th>${escape(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(v=>`<td>${escape(v)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
 return `<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><title>${escape(r.project.name)} 計算書</title><style>@page{size:A4;margin:15mm}body{font:11px/1.65 system-ui,"Noto Sans CJK TC",sans-serif;color:#193733}h1{font-size:24px}h2{margin-top:24px;font-size:16px}p,li{overflow-wrap:anywhere}table{width:100%;border-collapse:collapse;margin:10px 0}th,td{padding:6px;border:1px solid #ccd6d2;text-align:left;overflow-wrap:anywhere}th{background:#e9f0eb}thead{display:table-header-group}tr{break-inside:avoid}pre{white-space:pre-wrap;font-size:10px}.notice{border:1px solid #b58c4b;padding:12px;background:#fff8ea}</style></head><body><h1>${escape(r.project.name)}</h1><p>箱涵計算書｜1.0.0-alpha.1｜${r.mode==='envelope'?'離散車載包絡':'手動位置分析'}｜${r.cases} 工況</p><p class="notice">工程試算版：載重組合由使用者指定；規範整合與構材細部檢核尚未完成。N–M 斷面試算符合不代表箱涵設計合格。全部內力以 1 m 分析帶寬表示。</p><h2>一、輸入資料</h2><pre>${escape(JSON.stringify(r.project,null,2))}</pre><h2>二、內力包絡</h2>${table(['構件','Mmin kN·m/m','Mmax','Vmin kN/m','Vmax','Nmin kN/m','Nmax'],r.envelope.map(e=>[e.member,...[e.Mmin,e.Mmax,e.Vmin,e.Vmax,e.Nmin,e.Nmax].map(v=>num(v.value))]))}<h2>三、配筋斷面試算</h2>${table(['構件','雙面配筋','每面As mm²/m','N–M需求比','結果'],r.rc.map(v=>[v.member,`Ø${v.diameter} @ ${v.spacing??'—'} mm`,num(v.asPerFace),num(v.ratio),v.status]))}<h2>四、計算追溯與規範來源</h2>${r.trace.map(t=>`<h3>${escape(t.stage)}</h3><p>${escape(t.expression)}</p><p>${escape(t.detail)}</p><p>來源：${escape(t.source)}</p>`).join('')}<h2>五、控制工況</h2>${table(['構件','控制項','前軸x m','軸距 m','方向','工況'],r.envelope.flatMap(e=>(['Mmin','Mmax','Vmin','Vmax','Nmin','Nmax'] as const).map(k=>[e.member,k,num(e[k].position),num(e[k].spacing),e[k].direction,e[k].caseId])))}<h2>六、適用範圍與未完成項目</h2><ul>${r.warnings.map(w=>`<li>${escape(w)}</li>`).join('')}</ul></body></html>`;
}
/** Browser print keeps Traditional Chinese text selectable without bundling a proprietary font. */
export function printReport(r:Analysis){
 const frame=document.createElement('iframe');frame.style.cssText='position:fixed;right:0;bottom:0;width:0;height:0;border:0';document.body.append(frame);
 frame.onload=()=>{const win=frame.contentWindow;if(!win)return;win.addEventListener('afterprint',()=>frame.remove(),{once:true});void (win.document.fonts?.ready??Promise.resolve()).then(()=>{win.focus();win.print();});};
 frame.srcdoc=reportHtml(r);
}
